name: CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
  workflow_dispatch:

jobs:
  build_and_deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Set up JDK 11
        uses: actions/setup-java@v2
        with:
          java-version: '11'
          distribution: 'adopt'

      - name: Cache Maven dependencies
        uses: actions/cache@v2
        env:
          cache-name: maven
        with:
          path: ~/.m2/repository
          key: ${{ runner.os }}-build-${{ env.cache-name }}-${{ hashFiles('**/pom.xml') }}
          restore-keys: |
            ${{ runner.os }}-build-${{ env.cache-name }}-
            ${{ runner.os }}-build-
            ${{ runner.os }}-

      - name: Build with Maven
        run: mvn clean package

      - name: Move the built artifact
        if: github.ref == 'refs/heads/main'
        run: mv app/target/*.jar docker/

      - name: Start custom Docker builders (ARM & AMD) with Terraform
        if: github.ref == 'refs/heads/main'
        run: |
          export TF_VAR_aws_api_key='${{ secrets.AWS_API_KEY_1 }}'
          export TF_VAR_aws_api_secret='${{ secrets.AWS_API_SECRET_1 }}'
          ./.github/resources/scripts/start_terraform.sh

      - name: Set new AWS instances private key
        if: github.ref == 'refs/heads/main'
        run: |
          echo "⚙️ Set AWS AMI private key."
          AWS_AMI_PRIVATE_KEY_FILE=$(mktemp)
          echo "${{ secrets.AWS_AMI_PRIVATE_KEY }}" > $AWS_AMI_PRIVATE_KEY_FILE
          chmod 600 $AWS_AMI_PRIVATE_KEY_FILE
          echo "AWS_AMI_PRIVATE_KEY_FILE=$AWS_AMI_PRIVATE_KEY_FILE" >> $GITHUB_ENV

      - name: Wait for 60s
        if: github.ref == 'refs/heads/main'
        run: sleep 60s

      - name: Copy files
        if: github.ref == 'refs/heads/main'
        run: |
          ./.github/resources/scripts/copy_files.sh

      - name: Build Docker images on remote instances
        if: github.ref == 'refs/heads/main'
        run: |
          ./.github/resources/scripts/build_images.sh

      - name: Push images on Docker Hub
        if: github.ref == 'refs/heads/main'
        run: |
          export DOCKER_PASSWORD=${{ secrets.DOCKER_HUB_REGISTRY_PASSWORD }}
          ./.github/resources/scripts/push_images.sh

      - name: Push tags on Docker Hub
        if: github.ref == 'refs/heads/main'
        run: |
          export DOCKER_PASSWORD=${{ secrets.DOCKER_HUB_REGISTRY_PASSWORD }}
          ./.github/resources/scripts/push_tags.sh

      - name: Destroy Terraform infrastructure
        if: ${{ always() }}
        run: |
          export TF_VAR_aws_api_key='${{ secrets.AWS_API_KEY_1 }}'
          export TF_VAR_aws_api_secret='${{ secrets.AWS_API_SECRET_1 }}'
          ./.github/resources/scripts/destroy_terraform.sh
